### PR TITLE
added support for extendedKeyUsage and RSA key length

### PR DESCRIPTION
**Pull request by alisade**

### CODE REVIEW

**Comment by zuazo** [comment]
Hi @alisade,

Thanks for your PR :smile:

Please, could you update the README with your changes and fix the style tests?

RuboCop offenses:

```
$ rake style
Starting Foodcritic linting...
Completed!
Running RuboCop...
Inspecting 55 files
................................................CCC....

Offenses:

libraries/resource_ssl_certificate_generators.rb:34:7: C: Module has too many lines. [205/202]
      module Generators ...
      ^^^^^^^^^^^^^^^^^
libraries/resource_ssl_certificate_generators.rb:35:32: C: Surrounding space missing in default value assignment.
        def generate_key(length=2048)
                               ^
libraries/resource_ssl_certificate_generators.rb:151:9: C: Method has too many lines. [14/10]
        def generate_self_signed_cert_without_ca(key, cert, subject) ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libraries/resource_ssl_certificate_generators.rb:160:1: C: Trailing whitespace detected.
          
^^^^^^^^^^
libraries/resource_ssl_certificate_generators.rb:187:9: C: Method has too many lines. [15/10]
        def generate_self_signed_cert_with_ca(key, cert, subject, ca_cert_cont, ...
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libraries/resource_ssl_certificate_cert.rb:34:7: C: Module has too many lines. [209/202]
      module Cert ...
      ^^^^^^^^^^^
libraries/resource_ssl_certificate_key.rb:139:81: C: Line is too long. [82/80]
            read_namespace(%w(ssl_key length)) || read_namespace('length') || 2048
                                                                                ^^

55 files inspected, 7 offenses detected
RuboCop failed!
```

Besides that, adding an example [in the integration tests](https://github.com/zuazo/ssl_certificate-cookbook/tree/master/test/cookbooks/ssl_certificate_test/recipes) would be awesome, but not required.

See [TESTING](https://github.com/zuazo/ssl_certificate-cookbook/blob/master/TESTING.md) for some information about the tests. Feel free to ask me for help if you have doubts about them.

**Comment by hawkandbaby** [comment]
It appears to me that the two "Module has too many lines" errors will involve major refactoring. Would it be cleaner to accept the PR, then do a refactoring PR? 

Would two seperate commits in one PR suffice?

**Comment by zuazo** [comment]
Yes @hawkandbaby. Of course we can change the maximum module length in the [.rubocop.yml](https://github.com/zuazo/ssl_certificate-cookbook/blob/master/.rubocop.yml#L5-L6).

But, anyway, the other offenses need to be fixed and the documentation needs to be added to this PR.

**Comment by hawkandbaby** [comment]
It looks like the travis constraints need updating:
`rack-2.0.1 requires ruby version >= 2.2.2, which is incompatible with the
current version, ruby 2.2.0p0`

**Comment by zuazo** [comment]
@hawkandbaby thanks for your work.

Don't worry about travis. I going to check it manually :wink:

**Comment by zuazo** [comment]
Merged.

RuboCop configuration changed in 5cfbf177fd3e8a3654a27bdb3ed7190f6352508a, and unit and integration tests added in 9b0b7daa8e859beb3c974a1b64b907ae9f28a529.

**Comment by zuazo** [comment]
Released in [`2.0.0`](https://github.com/zuazo/ssl_certificate-cookbook/releases/tag/2.0.0)

**Pull request merged**
