### PR TITLE
Add support for ssl_certificate using CA with a passphrase

### PR DESCRIPTION
**Pull request by Annih**
Hello,

This PR aim to had support of Certificate Authority with passphrase to the `ssl_certificate`.
This is a basic implementation, with plain text pass phrase passed as attribute `ca_key_passphrase`.

I tried to add useful tests and a bit of documentation, but let me know if you want me to add more.

cc. @aboten

### CODE REVIEW

**Comment by zuazo** [comment]
Hello again @Annih :wink:

Thanks for all your work! Please, could you fix the RuboCop offenses?

```
Running RuboCop...

Inspecting 54 files

................CC.........C..........................

Offenses:

libraries/resource_ssl_certificate_cert.rb:33:7: C: Module has too many lines. [202/194]
      module Cert
      ^^^^^^
libraries/resource_ssl_certificate_generators.rb:181:9: C: Method has too many lines. [11/10]
        def generate_self_signed_cert_with_ca(key, cert, subject, ca_cert_cont,
        ^^^
libraries/resource_ssl_certificate_generators.rb:181:46: C: Avoid parameter lists longer than 5 parameters.
        def generate_self_signed_cert_with_ca(key, cert, subject, ca_cert_cont,
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
libraries/resource_ssl_certificate_generators.rb:184:13: C: Align the parameters of a method call if they span more than one line.
            ca_key_pass)
            ^^^^^^^^^^^
libraries/resource_ssl_certificate_generators.rb:196:26: C: Avoid parameter lists longer than 5 parameters.
        def generate_cert(key, subject, time, ca_cert_content = nil,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test/cookbooks/ssl_certificate_test/recipes/self_signed_with_ca_certificate.rb:83:21: C: Avoid comma after the last item of a hash.
  'time' => 10 * 365,
```

**Comment by Annih** [comment]
Hello @zuazo,

Okay, I'm on it, but ... because I'm adding the 6th parameters, I need to:
- either break the public interface - increasing the number of lines in the module
- either add a new method and do a lot of change

I'll try to do my best here!

**Comment by zuazo** [comment]
Hello @Annih,

Take the time you need. Let me know if you need help. I am very interested in this feature.

**Comment by zuazo** [comment]
@Annih thanks for your fantastic work :smile:

I have finished your work here and fixed all the conflicts before merging into master. All tests you have included have made my life easier. Thank you again for that.

Here is the final merge: ec0f8ab7a02be374fcbad286096030c4698b15b8

Oh! and my apologies for my unjustifiable delay.

**Comment by zuazo** [comment]
Released in [`1.12.0`](https://github.com/zuazo/ssl_certificate-cookbook/releases/tag/1.12.0).

**Pull request merged**
